version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"